# la liga players database - sample data for demonstration
# in production, this would be generated by scraper.py

laliga_players = [
    # real madrid players
    {
        "name": "Vinícius Junior",
        "team": "Real Madrid",
        "position": "LW",
        "age": 24,
        "nationality": "Brazil",
        "market_value": 120.0,
        "url": "https://www.transfermarkt.us/vinicius-junior/profil/spieler/371998"
    },
    {
        "name": "Jude Bellingham",
        "team": "Real Madrid", 
        "position": "CM",
        "age": 21,
        "nationality": "England",
        "market_value": 180.0,
        "url": "https://www.transfermarkt.us/jude-bellingham/profil/spieler/581678"
    },
    {
        "name": "Kylian Mbappé",
        "team": "Real Madrid",
        "position": "ST",
        "age": 25,
        "nationality": "France", 
        "market_value": 180.0,
        "url": "https://www.transfermarkt.us/kylian-mbappe/profil/spieler/342229"
    },
    {
        "name": "Rodrygo",
        "team": "Real Madrid",
        "position": "RW",
        "age": 23,
        "nationality": "Brazil",
        "market_value": 90.0,
        "url": "https://www.transfermarkt.us/rodrygo/profil/spieler/412363"
    },
    {
        "name": "Aurelien Tchouameni",
        "team": "Real Madrid",
        "position": "DM",
        "age": 24,
        "nationality": "France",
        "market_value": 90.0,
        "url": "https://www.transfermarkt.us/aurelien-tchouameni/profil/spieler/458654"
    },
    # atletico madrid players
    {
        "name": "Antoine Griezmann",
        "team": "Atletico Madrid",
        "position": "AM",
        "age": 33,
        "nationality": "France",
        "market_value": 20.0,
        "url": "https://www.transfermarkt.us/antoine-griezmann/profil/spieler/125781"
    },
    {
        "name": "João Félix",
        "team": "Atletico Madrid",
        "position": "AM",
        "age": 24,
        "nationality": "Portugal",
        "market_value": 60.0,
        "url": "https://www.transfermarkt.us/joao-felix/profil/spieler/462250"
    },
    {
        "name": "José Giménez",
        "team": "Atletico Madrid",
        "position": "CB",
        "age": 29,
        "nationality": "Uruguay",
        "market_value": 25.0,
        "url": "https://www.transfermarkt.us/jose-gimenez/profil/spieler/197613"
    },
    # sevilla players
    {
        "name": "Youssef En-Nesyri",
        "team": "Sevilla",
        "position": "ST",
        "age": 27,
        "nationality": "Morocco",
        "market_value": 25.0,
        "url": "https://www.transfermarkt.us/youssef-en-nesyri/profil/spieler/348943"
    },
    {
        "name": "Jules Koundé",
        "team": "Sevilla",
        "position": "CB",
        "age": 25,
        "nationality": "France",
        "market_value": 60.0,
        "url": "https://www.transfermarkt.us/jules-kounde/profil/spieler/411975"
    },
    # villarreal players
    {
        "name": "Alexander Sørloth",
        "team": "Villarreal",
        "position": "ST",
        "age": 28,
        "nationality": "Norway",
        "market_value": 30.0,
        "url": "https://www.transfermarkt.us/alexander-sorloth/profil/spieler/295403"
    },
    {
        "name": "Álex Baena",
        "team": "Villarreal",
        "position": "LW",
        "age": 23,
        "nationality": "Spain",
        "market_value": 40.0,
        "url": "https://www.transfermarkt.us/alex-baena/profil/spieler/636652"
    },
    {
        "name": "Pau Torres",
        "team": "Villarreal",
        "position": "CB",
        "age": 27,
        "nationality": "Spain",
        "market_value": 45.0,
        "url": "https://www.transfermarkt.us/pau-torres/profil/spieler/418560"
    },
    # real sociedad players  
    {
        "name": "Martin Zubimendi",
        "team": "Real Sociedad",
        "position": "DM",
        "age": 25,
        "nationality": "Spain",
        "market_value": 60.0,
        "url": "https://www.transfermarkt.us/martin-zubimendi/profil/spieler/401500"
    },
    {
        "name": "Mikel Oyarzabal",
        "team": "Real Sociedad",
        "position": "LW",
        "age": 27,
        "nationality": "Spain",
        "market_value": 50.0,
        "url": "https://www.transfermarkt.us/mikel-oyarzabal/profil/spieler/296080"
    },
    {
        "name": "Alexander Isak",
        "team": "Real Sociedad",
        "position": "ST",
        "age": 25,
        "nationality": "Sweden",
        "market_value": 70.0,
        "url": "https://www.transfermarkt.us/alexander-isak/profil/spieler/424630"
    },
    # valencia players
    {
        "name": "Carlos Soler",
        "team": "Valencia",
        "position": "CM",
        "age": 27,
        "nationality": "Spain",
        "market_value": 25.0,
        "url": "https://www.transfermarkt.us/carlos-soler/profil/spieler/345205"
    },
    {
        "name": "José Gayà",
        "team": "Valencia",
        "position": "LB",
        "age": 29,
        "nationality": "Spain",
        "market_value": 20.0,
        "url": "https://www.transfermarkt.us/jose-gaya/profil/spieler/201989"
    },
    # real betis players
    {
        "name": "Nabil Fekir",
        "team": "Real Betis",
        "position": "AM",
        "age": 31,
        "nationality": "France",
        "market_value": 15.0,
        "url": "https://www.transfermarkt.us/nabil-fekir/profil/spieler/203496"
    },
    {
        "name": "Sergio Canales",
        "team": "Real Betis",
        "position": "CM",
        "age": 33,
        "nationality": "Spain",
        "market_value": 8.0,
        "url": "https://www.transfermarkt.us/sergio-canales/profil/spieler/71842"
    },
    # athletic bilbao players
    {
        "name": "Nico Williams",
        "team": "Athletic Bilbao",
        "position": "LW",
        "age": 22,
        "nationality": "Spain",
        "market_value": 60.0,
        "url": "https://www.transfermarkt.us/nico-williams/profil/spieler/544693"
    },
    {
        "name": "Iñaki Williams",
        "team": "Athletic Bilbao",
        "position": "RW",
        "age": 30,
        "nationality": "Spain",
        "market_value": 30.0,
        "url": "https://www.transfermarkt.us/inaki-williams/profil/spieler/227645"
    },
    # getafe players
    {
        "name": "Borja Mayoral",
        "team": "Getafe",
        "position": "ST",
        "age": 27,
        "nationality": "Spain",
        "market_value": 18.0,
        "url": "https://www.transfermarkt.us/borja-mayoral/profil/spieler/315711"
    },
    # osasuna players
    {
        "name": "Ante Budimir",
        "team": "Osasuna",
        "position": "ST",
        "age": 32,
        "nationality": "Croatia",
        "market_value": 8.0,
        "url": "https://www.transfermarkt.us/ante-budimir/profil/spieler/150075"
    },
    # celta vigo players
    {
        "name": "Iago Aspas",
        "team": "Celta Vigo",
        "position": "ST",
        "age": 37,
        "nationality": "Spain",
        "market_value": 4.0,
        "url": "https://www.transfermarkt.us/iago-aspas/profil/spieler/51784"
    },
    # rayo vallecano players
    {
        "name": "Álvaro García",
        "team": "Rayo Vallecano",
        "position": "LW",
        "age": 31,
        "nationality": "Spain",
        "market_value": 5.0,
        "url": "https://www.transfermarkt.us/alvaro-garcia/profil/spieler/159068"
    },
    # mallorca players
    {
        "name": "Vedat Muriqi",
        "team": "Mallorca",
        "position": "ST",
        "age": 30,
        "nationality": "Kosovo",
        "market_value": 8.0,
        "url": "https://www.transfermarkt.us/vedat-muriqi/profil/spieler/138790"
    },
    # girona players
    {
        "name": "Artem Dovbyk",
        "team": "Girona",
        "position": "ST",
        "age": 26,
        "nationality": "Ukraine",
        "market_value": 30.0,
        "url": "https://www.transfermarkt.us/artem-dovbyk/profil/spieler/515803"
    },
    {
        "name": "Savinho",
        "team": "Girona",
        "position": "RW",
        "age": 20,
        "nationality": "Brazil",
        "market_value": 40.0,
        "url": "https://www.transfermarkt.us/savinho/profil/spieler/736166"
    },
    # las palmas players
    {
        "name": "Alberto Moleiro",
        "team": "Las Palmas",
        "position": "AM",
        "age": 21,
        "nationality": "Spain",
        "market_value": 15.0,
        "url": "https://www.transfermarkt.us/alberto-moleiro/profil/spieler/767665"
    },
    # alaves players
    {
        "name": "Luis Rioja",
        "team": "Alaves",
        "position": "LW",
        "age": 30,
        "nationality": "Spain",
        "market_value": 6.0,
        "url": "https://www.transfermarkt.us/luis-rioja/profil/spieler/179361"
    },
    # espanyol players
    {
        "name": "Martin Braithwaite",
        "team": "Espanyol",
        "position": "ST",
        "age": 33,
        "nationality": "Denmark",
        "market_value": 3.0,
        "url": "https://www.transfermarkt.us/martin-braithwaite/profil/spieler/95732"
    },
    # leganes players
    {
        "name": "Miguel de la Fuente",
        "team": "Leganes",
        "position": "ST",
        "age": 24,
        "nationality": "Spain",
        "market_value": 4.0,
        "url": "https://www.transfermarkt.us/miguel-de-la-fuente/profil/spieler/636705"
    },
    # valladolid players
    {
        "name": "Mamadou Sylla",
        "team": "Valladolid",
        "position": "ST",
        "age": 25,
        "nationality": "Guinea",
        "market_value": 3.5,
        "url": "https://www.transfermarkt.us/mamadou-sylla/profil/spieler/473205"
    }
]

def get_all_players():
    """return all la liga players"""
    return laliga_players

def search_players(query):
    """search players by name"""
    query_lower = query.lower()
    return [p for p in laliga_players if query_lower in p['name'].lower()]

def get_players_by_position(position):
    """get players by position"""
    return [p for p in laliga_players if p['position'] == position.upper()]

def get_players_by_team(team_name):
    """get players by team"""
    return [p for p in laliga_players if team_name.lower() in p['team'].lower()]

def get_player_names():
    """get list of all player names for autocomplete"""
    return [p['name'] for p in laliga_players]